# Generated by Django 5.2.1 on 2025-08-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('stage', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offered', 'Offered')], max_length=100)),
                ('position', models.CharField(max_length=300)),
                ('apply_date', models.DateField()),
                ('response_date', models.DateField()),
                ('job_url', models.URLField()),
                ('referral', models.BooleanField(default=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
